name: flutter_camera
description: A Flutter project for camera functionality.
publish_to: none
version: 0.1.0

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  camera: ^0.10.5+4
  flutter:
    sdk: flutter
  image: ^3.0.1
  image_picker: ^0.8.4+4
  path_provider: ^2.1.1
  video_player: ^2.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
